### ISSUE TITLE
Latest version not starting

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#7]
crash on startup, nothing useful in log

```
Traceback (most recent call last):
  File "/home/tom/neumodvb/gui/neumodvb.py", line 625, in OnInit
    self.frame = neumoMainFrame(self, None, wx.ID_ANY, "")
  File "/home/tom/neumodvb/gui/neumodvb.py", line 82, in __init__
    self.satlist_panel, self.frontendlist_panel, self.statuslist_panel,
AttributeError: 'neumoMainFrame' object has no attribute 'statuslist_panel'
OnInit returned false, exiting...
```

**Comment by deeptho** [comment]
I will soon upload a new version. The offending commit should not yet have been included
